server:
  port: 0

spring:
  application:
    name: user-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  h2:
    console:
      settings:
        web-allow-others: true
      path: /user-service/h2-console
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/test;AUTO_SERVER=true
#    username: sa
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: Welcome to the simple e-commerce.


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
logging:
  level:
    com.example.userservice.client: debug
